export const ENV_FILE_PATH: string = 'development.env';
export const MYSQL: 'mysql' = 'mysql' as const;
export const MILLISECONDS_IN_A_MINUTE: number = 60 * 1000;
export const DATE_FORMAT: string = 'yyyy-MM-dd HH:mm:ss';
export const HEADER_CONTENT_TYPE: string = 'content-type';
export const HEADER_CONTENT_DISPOSITION: string = 'content-disposition';
export const FILENAME_IN_CONTENT_DISPOSITION: string = 'filename=';
export const HEADER_LOCATION: string = 'location';
export const SLASH: string = '/';
export const HEADER_API_KEY: string = 'x-api-key';
export const API_KEY_AUTH_NAME: string = 'Api-Key';
export const BEARER: string = 'Bearer';
export const USER: string = 'user';
export const JWT_AUTH_NAME: string = 'JWT';
