export enum EnvEnum {
  MYSQL_DATABASE = 'MYSQL_DATABASE',
  MYSQL_USER = 'MYSQL_USER',
  MYSQL_ROOT_PASSWORD = 'MYSQL_ROOT_PASSWORD',
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_SYNCHRONIZE = 'MYSQL_SYNCHRONIZE',
  APP_PORT = 'APP_PORT',
}
